changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
    - title: Fixes and improvements 🐛
      labels:
        - Semver-Patch
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"