categories:
  - title: '機能追加'
    labels:
      - '機能追加'
  - title: '機能改善'
    labels:
      - '機能改善'
  - title: '不具合修正'
    labels:
      - '不具合修正'
  - title: '監視エラー'
    labels:
      - '監視エラー'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'exclude from changelog'