name: Production Release

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  update_config:
    runs-on: ubuntu-latest
    # Job 全体のタイムアウト時間を指定
    timeout-minutes: 5
    steps:
      # 開発用ブランチを指定
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: "develop"
      - name: Check if main branch has new commits
        id: check_commits
        run: |
          git fetch origin
          FU_KK=$(git diff origin/develop..origin/staging)
          echo "$FU_KK"
          # if [ "$SOURCE_BRANCH" == "$TARGET_BRANCH" ]; then
          #   echo "has_commits=false" >> $GITHUB_ENV
          # else
          #   echo "has_commits=true" >> $GITHUB_ENV
          # fi
      - name: Create pull request and tag
        if: env.has_commits == 'true'
        shell: bash
        # まずDraft状態で作成する。
        run: |
          env
          PR_TITLE="Release at $(TZ='JST-9' date --date "8 days" +%Y.%m.%d)"
          TAG_VERSION=express_$(date --date "8 days" +%Y%m%d)
          ASSIGNEE="ji-liu"
          REVIEWER="ji-liu"

          gh pr create -d --base "staging" --title "$PR_TITLE" --body "Auto-generated pull request, not generated " --assignee "$ASSIGNEE" --reviewer "$REVIEWER"
          git tag $TAG_VERSION -m "Release $TAG_VERSION"
          git push origin $TAG_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}