name: Production Release

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  update_config:
    runs-on: ubuntu-latest
    # Job 全体のタイムアウト時間を指定
    timeout-minutes: 5
    steps:
      # 開発用ブランチを指定
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: "develop"
      - name: Check if main branch has new commits
        id: check_commits
        run: |
          git fetch origin
          git diff --quiet origin/staging origin/develop
          if [ $? -eq 1 ]; then
            echo "has_diff=true" >> $GITHUB_ENV
            exit 0
          else
            echo "has_diff=false" >> $GITHUB_ENV
          fi
      - name: Create pull request
        if: env.has_diff == 'true'
        shell: bash
        # まずDraft状態で作成する。
        run: |
          PR_TITLE="Release at $(TZ='JST-9' date --date "8 days" +%Y.%m.%d)"
          ASSIGNEE="ji-liu"
          REVIEWER="ji-liu"

          gh pr create -d --base "staging" --title "$PR_TITLE" --body "Auto-generated pull request, not generated " --assignee "$ASSIGNEE" --reviewer "$REVIEWER"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}